// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.3.1

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCommentAddCommentsToAnArticle = "/realworld.v1.Comment/AddCommentsToAnArticle"
const OperationCommentDeleteComment = "/realworld.v1.Comment/DeleteComment"
const OperationCommentGetCommentsFromAnArticle = "/realworld.v1.Comment/GetCommentsFromAnArticle"

type CommentHTTPServer interface {
	AddCommentsToAnArticle(context.Context, *AddCommentsToAnArticleRequest) (*AddCommentsToAnArticleResponse, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	GetCommentsFromAnArticle(context.Context, *GetCommentsFromAnArticleRequest) (*GetCommentsFromAnArticleResponse, error)
}

func RegisterCommentHTTPServer(s *http.Server, srv CommentHTTPServer) {
	r := s.Route("/")
	r.POST("/api/articles/{slug}/comments", _Comment_AddCommentsToAnArticle0_HTTP_Handler(srv))
	r.GET("/api/articles/{slug}/comments", _Comment_GetCommentsFromAnArticle0_HTTP_Handler(srv))
	r.DELETE("/api/articles/{slug}/comments/{id}", _Comment_DeleteComment0_HTTP_Handler(srv))
}

func _Comment_AddCommentsToAnArticle0_HTTP_Handler(srv CommentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddCommentsToAnArticleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentAddCommentsToAnArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddCommentsToAnArticle(ctx, req.(*AddCommentsToAnArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddCommentsToAnArticleResponse)
		return ctx.Result(200, reply)
	}
}

func _Comment_GetCommentsFromAnArticle0_HTTP_Handler(srv CommentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCommentsFromAnArticleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentGetCommentsFromAnArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCommentsFromAnArticle(ctx, req.(*GetCommentsFromAnArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCommentsFromAnArticleResponse)
		return ctx.Result(200, reply)
	}
}

func _Comment_DeleteComment0_HTTP_Handler(srv CommentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCommentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommentDeleteComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteComment(ctx, req.(*DeleteCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCommentResponse)
		return ctx.Result(200, reply)
	}
}

type CommentHTTPClient interface {
	AddCommentsToAnArticle(ctx context.Context, req *AddCommentsToAnArticleRequest, opts ...http.CallOption) (rsp *AddCommentsToAnArticleResponse, err error)
	DeleteComment(ctx context.Context, req *DeleteCommentRequest, opts ...http.CallOption) (rsp *DeleteCommentResponse, err error)
	GetCommentsFromAnArticle(ctx context.Context, req *GetCommentsFromAnArticleRequest, opts ...http.CallOption) (rsp *GetCommentsFromAnArticleResponse, err error)
}

type CommentHTTPClientImpl struct {
	cc *http.Client
}

func NewCommentHTTPClient(client *http.Client) CommentHTTPClient {
	return &CommentHTTPClientImpl{client}
}

func (c *CommentHTTPClientImpl) AddCommentsToAnArticle(ctx context.Context, in *AddCommentsToAnArticleRequest, opts ...http.CallOption) (*AddCommentsToAnArticleResponse, error) {
	var out AddCommentsToAnArticleResponse
	pattern := "/api/articles/{slug}/comments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCommentAddCommentsToAnArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *CommentHTTPClientImpl) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...http.CallOption) (*DeleteCommentResponse, error) {
	var out DeleteCommentResponse
	pattern := "/api/articles/{slug}/comments/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommentDeleteComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *CommentHTTPClientImpl) GetCommentsFromAnArticle(ctx context.Context, in *GetCommentsFromAnArticleRequest, opts ...http.CallOption) (*GetCommentsFromAnArticleResponse, error) {
	var out GetCommentsFromAnArticleResponse
	pattern := "/api/articles/{slug}/comments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommentGetCommentsFromAnArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
