// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"realworld-go-kratos/internal/biz"
	"realworld-go-kratos/internal/conf"
	"realworld-go-kratos/internal/data"
	"realworld-go-kratos/internal/server"
	"realworld-go-kratos/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepositoryIface := data.NewRealWorldRepository(dataData, logger)
	realWorldUsecase := biz.NewRealWorldUsecase(userRepositoryIface, logger)
	realWorldService := service.NewRealWorldServiceService(realWorldUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, realWorldService, logger)
	grpcServer := server.NewGRPCServer(confServer, realWorldService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
